const ADD_ANIME_WATCHLIST_START = 'ADD_ANIME_WATCHLIST_START';
const ADD_ANIME_WATCHLIST_SUCCESS = 'ADD_ANIME_WATCHLIST_SUCCESS';
const ADD_ANIME_WATCHLIST_FAIL = 'ADD_ANIME_WATCHLIST_FAIL';
const GET_ANIME_WATCHLIST_START = 'GET_ANIME_WATCHLIST_START';
const GET_ANIME_WATCHLIST_SUCCESS = 'GET_ANIME_WATCHLIST_SUCCESS';
const GET_ANIME_WATCHLIST_FAIL = 'GET_ANIME_WATCHLIST_FAIL';
const SET_ANIME_ID = 'SET_ANIME_ID';
const DELETE_ANIME_WATCHLIST_START = 'DELETE_ANIME_WATCHLIST_START';
const DELETE_ANIME_WATCHLIST_SUCCESS = 'DELETE_ANIME_WATCHLIST_SUCCESS';
const DELETE_ANIME_WATCHLIST_FAIL = 'DELETE_ANIME_WATCHLIST_FAIL';
const SET_ANIME_DIALOG_DETAIL = 'SET_ANIME_DIALOG_DETAIL';
const ANIME_STATUS_SAVE_START = 'ANIME_STATUS_SAVE_START';
const ANIME_STATUS_SAVE_SUCCESS = 'ANIME_STATUS_SAVE_SUCCESS';
const ANIME_STATUS_SAVE_FAIL = 'ANIME_STATUS_SAVE_FAIL';

export {
  ADD_ANIME_WATCHLIST_START,
  ADD_ANIME_WATCHLIST_SUCCESS,
  ADD_ANIME_WATCHLIST_FAIL,
  GET_ANIME_WATCHLIST_FAIL,
  GET_ANIME_WATCHLIST_START,
  GET_ANIME_WATCHLIST_SUCCESS,
  SET_ANIME_ID,
  DELETE_ANIME_WATCHLIST_START,
  DELETE_ANIME_WATCHLIST_SUCCESS,
  DELETE_ANIME_WATCHLIST_FAIL,
  SET_ANIME_DIALOG_DETAIL,
  ANIME_STATUS_SAVE_START,
  ANIME_STATUS_SAVE_SUCCESS,
  ANIME_STATUS_SAVE_FAIL,
};
