const LOGIN_API_START = "LOGIN_API_START";
const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
const LOGIN_API_FAIL = "LOGIN_API_FAIL";
const REGISTER_API_START = "REGISTER_API_START";
const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
const REGISTER_API_FAIL = "REGISTER_API_FAIL";
const GET_ME_API_START = "GET_ME_API_START";
const GET_ME_API_SUCCESS = "GET_ME_API_SUCCESS";
const GET_ME_API_FAIL = "GET_ME_API_FAIL";
const LOGOUT_USER_START = "LOGOUT_USER_START";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
const RESET_ALL = "RESET_ALL";

export const AUTH = {
  LOGIN_API_START,
  LOGIN_API_SUCCESS,
  LOGIN_API_FAIL,
  REGISTER_API_START,
  REGISTER_API_SUCCESS,
  REGISTER_API_FAIL,
  GET_ME_API_START,
  GET_ME_API_SUCCESS,
  GET_ME_API_FAIL,
  LOGOUT_USER_START,
  LOGOUT_USER_SUCCESS,
  RESET_ALL,
};
